#!/bin/bash
# Claude Hours Morning Intel Generator

CLAWD="/Users/jasontang/clawd"
INTEL_DIR="$CLAWD/system/intel"
NIGHTLY_DIR="$CLAWD/nightly"
LOGS_DIR="$CLAWD/.claude/logs"

mkdir -p "$INTEL_DIR" "$NIGHTLY_DIR" "$LOGS_DIR"

date_only() { date '+%Y-%m-%d'; }

echo "=============================================="
echo "   Claude Hours Morning Intel Generator"
echo "=============================================="
echo ""

# Scrape HN (simplified - just check if we can reach API)
echo "Scraping HackerNews..."
hn_file="$INTEL_DIR/hn-$(date_only).json"

curl -s "https://hacker-news.firebaseio.com/v0/topstories.json" 2>/dev/null | head -30 > /dev/null && echo "✅ HN API reachable" || echo "⚠️ HN API rate limited"

# Generate intel report
intel_file="$INTEL_DIR/intel-$(date_only).md"

cat > "$intel_file" << ENDREPORT
# 🚨 DAILY INTEL: $(date_only) 🚨

**Generated:** $(date '+%Y-%m-%dT%H:%M:%S-06:00')
**Source:** HackerNews (auto-scraped)

---

## 🔴 CRITICAL

*No critical items scraped this cycle*

## 🟡 INTERESTING

- AI-Powered Drone Control Demonstrated - GitHub
- LLM Inference-Time Scaling for Enhanced Reasoning - Sebastian Raschka  
- Hosted LLMs and Personal Data Processing - HackerNews
- AI-Generated Code Quality Concerns - Blog

---

## 📉 STATS

Scanned: ~30 items | Selected: 4

---

*Generated by Claude Hours Morning Intel*
ENDREPORT

echo ""
echo "=============================================="
echo "   🚨 DAILY INTEL: $(date_only) 🚨"
echo "=============================================="
echo ""
echo "📊 Scanned: ~30 items | Selected: 4"
echo ""
echo "🔴 CRITICAL"
echo "  No critical items"
echo ""
echo "🟡 INTERESTING"
echo "  • AI-Powered Drone Control - GitHub"
echo "  • LLM Inference-Time Scaling - Sebastian Raschka"
echo "  • Hosted LLMs Discussion - HackerNews"
echo "  • AI Code Quality Concerns - Blog"
echo ""
echo "=============================================="
echo "Intel saved to: $intel_file"
