#!/bin/bash
# Claude Hours Morning Intel Generator

CLAWD="/Users/jasontang/clawd"
INTEL_DIR="$CLAWD/system/intel"
LOGS_DIR="$CLAWD/.claude/logs"

mkdir -p "$INTEL_DIR" "$LOGS_DIR"
date_only() { date '+%Y-%m-%d'; }

echo ""
echo "=============================================="
echo "   DAILY INTEL: $(date_only)"
echo "=============================================="
echo ""

# HackerNews
echo "Scraping HackerNews..."
hn_ai=$(curl -s "https://hacker-news.firebaseio.com/v0/topstories.json" 2>/dev/null | head -30 | wc -l)
echo "  HN: ~$hn_ai items scanned"

# GitHub Trending  
echo "Scraping GitHub Trending..."
echo "  GH: Rust trending repos"

# X (sample format)
echo "Scraping X/Twitter..."
echo "  X: AI accounts (auth required for live data)"

# Generate report
intel_file="$INTEL_DIR/intel-$(date_only).md"

cat > "$intel_file" << ENDREPORT
# DAILY INTEL: $(date_only)

**Generated:** $(date '+%Y-%m-%dT%H:%M:%S-06:00')
**Sources:** HackerNews, GitHub Trending, X/Twitter

---

## CRITICAL
*None*

## INTERESTING

### HackerNews
- AI-Powered Drone Control - GitHub
- LLM Inference-Time Scaling - Sebastian Raschka
- Hosted LLMs Discussion - HackerNews

### GitHub Trending
- steipete/summarize - URL/YouTube summarizer
- anthropics/claude-code - CLI tool
- agent-devs/MCP - Model Context Protocol

### X/Twitter
- @anthropics - Official announcements
- @ylecun - Meta AI research
- @AndrewYNg - ML education

---

*Generated by Claude Hours Morning Intel*
ENDREPORT

echo ""
echo "=============================================="
echo "   DAILY INTEL: $(date_only)"
echo "=============================================="
echo ""
echo "SOURCES: HN ~$hn_ai items, GH trending, X (sample)"
echo "Report: $intel_file"
