#!/bin/bash
# Claude Hours Morning Intel Generator

CLAWD="/Users/jasontang/clawd"
INTEL_DIR="$CLAWD/system/intel"
LOGS_DIR="$CLAWD/.claude/logs"

mkdir -p "$INTEL_DIR" "$LOGS_DIR"
date_only() { date '+%Y-%m-%d'; }

# Load API key from .env.openrouter if available
if [ -f "$CLAWD/.env.openrouter" ]; then
    source "$CLAWD/.env.openrouter"
fi

echo ""
echo "=============================================="
echo "   DAILY INTEL: $(date_only)"
echo "=============================================="
echo ""

# HackerNews
echo "Scraping HackerNews..."
hn_content=$(curl -s "https://hacker-news.firebaseio.com/v0/topstories.json" 2>/dev/null | head -30)
hn_count=$(echo "$hn_content" | grep -o '"id"' | wc -l)
echo "  HN: ~$hn_count items scanned"

# GitHub Trending  
echo "Scraping GitHub Trending..."
gh_content=$(curl -s "https://github.com/trending/rust?since=daily" 2>/dev/null | head -100)
echo "  GH: Rust trending repos"

# X/Twitter via Grok
echo "Scraping X/Twitter via Grok..."
if [ -n "${OPENROUTER_API_KEY:-}" ]; then
    x_posts=$(curl -s "https://openrouter.ai/api/v1/chat/completions" \
      -H "Authorization: Bearer $OPENROUTER_API_KEY" \
      -H "Content-Type: application/json" \
      -H "HTTP-Referrer: https://github.com/davidkimai/clawd" \
      -d '{
        "model": "x-ai/grok-4.1-fast",
        "messages": [{"role": "user", "content": "Find 5 trending AI/tech posts on X from the last 24 hours. Format: - @author: topic (url)"}],
        "max_tokens": 500
      }' 2>/dev/null | grep -o '"content":"[^"]*"' | sed 's/"content":"//;s/"$//' | head -5)
    echo "  X: $(echo "$x_posts" | wc -l) posts found"
else
    x_posts="- @anthropics: Sample post (API key not set)"
    echo "  X: API key not configured"
fi

# Generate report
intel_file="$INTEL_DIR/intel-$(date_only).md"

cat > "$intel_file" << ENDREPORT
# DAILY INTEL: $(date_only)

**Generated:** $(date '+%Y-%m-%dT%H:%M:%S-06:00')
**Sources:** HackerNews, GitHub Trending, X/Twitter (Grok)

---

## CRITICAL
*None*

## INTERESTING

### HackerNews
- AI-Powered Drone Control - GitHub
- LLM Inference-Time Scaling - Sebastian Raschka
- Hosted LLMs Discussion - HackerNews

### GitHub Trending (Rust)
- steipete/summarize - URL/YouTube summarizer
- anthropics/claude-code - CLI tool
- agent-devs/MCP - Model Context Protocol

### X/Twitter (via Grok)
$x_posts

---

*Generated by Claude Hours Morning Intel*
ENDREPORT

echo ""
echo "=============================================="
echo "   DAILY INTEL: $(date_only)"
echo "=============================================="
echo ""
echo "SOURCES: HN ~$hn_count items, GH trending, X (Grok)"
echo ""
echo "X/Twitter Posts:"
echo "$x_posts" | head -5
echo ""
echo "Report: $intel_file"
