#!/bin/bash
# Claude Hours Link Ingestor using @steipete/summarize

CLAWD="/Users/jasontang/clawd"
INTEL_DIR="$CLAWD/system/intel/links"
MEMORY_DIR="$CLAWD/memory"
LOGS_DIR="$CLAWD/.claude/logs"

mkdir -p "$INTEL_DIR" "$MEMORY_DIR" "$LOGS_DIR"

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] [LINK] $1" >> "$LOGS_DIR/link-ingestor.log"; }

date_only() { date '+%Y-%m-%d'; }
timestamp() { date '+%Y-%m-%dT%H:%M:%S-06:00'; }

# Summarize a link
summarize_link() {
    local url="$1"
    local length="${2:-medium}"
    local output_file="$INTEL_DIR/summary-$(date_only)-$(echo "$url" | md5 | cut -c1-8).md"
    
    echo "Ingesting: $url"
    log "Ingesting: $url"
    
    local start_time=$(date +%s)
    
    if result=$(summarize "$url" --length "$length" 2>&1); then
        local end_time=$(date +%s)
        local duration=$((end_time - start_time))
        
        cat > "$output_file" << EOF
# Link Summary: $(date_only)

**URL:** $url
**Generated:** $(timestamp)
**Duration:** ${duration}s

---

$result

---
*Generated by Claude Hours Link Ingestor*
EOF
        
        echo "Summary saved: $output_file ($duration s)"
        log "Complete: $output_file"
        
        # Append to memory
        cat >> "$MEMORY_DIR/ingested-links.md" << EOF

---

## $(date_only): $url

$result

EOF
        
        echo "$output_file"
    else
        echo "Warning: $result"
        log "Warning: $result"
    fi
}

# Main
case "${1:-}" in
    "")
        echo "Usage: $0 <url> [length]"
        echo "  $0 \"https://github.com/user/repo\""
        echo "  $0 \"https://youtube.com/watch?v=...\" medium"
        echo "  $0 recent"
        echo "  $0 memory"
        ;;
    recent)
        ls -t "$INTEL_DIR"/summary-*.md 2>/dev/null | head -5 | while read f; do
            basename "$f"
        done
        ;;
    memory)
        cat "$MEMORY_DIR/ingested-links.md" 2>/dev/null || echo "No links yet"
        ;;
    *)
        summarize_link "$1" "${2:-medium}"
        ;;
esac
