#!/bin/bash
#
# Claude Hours Skill Generator
# Creates new skills based on context, patterns, and identified gaps
#

set -euo pipefail

CLAWD="/Users/jasontang/clawd"
SKILLS_DIR="$CLAWD/skills"
STATE_DIR="$CLAWD/.claude/state"
TRACKING_FILE="$STATE_DIR/skill-progress.json"
LEARNING_DIR="$CLAWD/system/learning"

mkdir -p "$SKILLS_DIR" "$STATE_DIR" "$LEARNING_DIR"

log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] [SKILL-GEN] $1" >> "$LEARNING_DIR/skill-generator.log"; }
error() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] [SKILL-GEN] ERROR: $1" >> "$LEARNING_DIR/skill-generator.log"; }

# === ANALYZE CONTEXT FOR SKILL NEEDS ===
analyze_context() {
    log "Analyzing context for skill needs..."
    
    local recent_tasks=$(cat "$STATE_DIR/current-session.json" 2>/dev/null | jq -r '.tasks_completed[]?.task' 2>/dev/null | head -20)
    local memory_log=$(cat "$STATE_DIR/memory.log" 2>/dev/null | tail -30)
    local chat_history=$(cat "$STATE_DIR/chat-context.json" 2>/dev/null | tail -50)
    
    # Look for patterns indicating skill needs
    local patterns=()
    
    # Check for repeated tasks
    if echo "$recent_tasks" | grep -q "Research"; then
        patterns+=("research")
    fi
    if echo "$recent_tasks" | grep -q "Document"; then
        patterns+=("documentation")
    fi
    if echo "$recent_tasks" | grep -q "Code\|Build"; then
        patterns+=("coding")
    fi
    if echo "$memory_log" | grep -q "analysis"; then
        patterns+=("analysis")
    fi
    
    # Check for "I need to" patterns indicating capability gaps
    local capability_gaps=$(grep -r "I need to\|Can you\|How do I" "$MEMORY_DIR"/*.md 2>/dev/null | \
        grep -oE "to [a-z]+|[a-z]+ (for|to)" | \
        sort -u | head -5)
    
    log "Context analysis complete. Patterns found: ${patterns[*]}"
    
    # Return unique patterns
    echo "${patterns[@]}" | tr ' ' '\n' | sort -u | grep -v '^$' | tr '\n' ' '
}

# === IDENTIFY SKILL GAPS ===
identify_skill_gaps() {
    log "Identifying skill gaps..."
    
    local existing_skills=$(ls "$SKILLS_DIR" 2>/dev/null | grep -v "^_\|^system" | head -20)
    local needed_patterns=("web_search" "file_operations" "api_integration" "data_processing" "automation")
    
    local gaps=()
    
    for pattern in "${needed_patterns[@]}"; do
        if ! echo "$existing_skills" | grep -qi "$pattern"; then
            gaps+=("$pattern")
        fi
    done
    
    echo "${gaps[@]}" | tr ' ' '\n' | grep -v '^$'
}

# === GENERATE SKILL FROM PATTERN ===
generate_skill() {
    local skill_name="$1"
    local skill_dir="$SKILLS_DIR/${skill_name// /-}"
    
    log "Generating skill: $skill_name"
    
    mkdir -p "$skill_dir"
    
    # Generate SKILL.md
    cat > "$skill_dir/SKILL.md" << EOF
# $skill_name

**Created:** $(date '+%Y-%m-%d')
**Source:** Auto-generated by Claude Hours Skill Generator
**Status:** experimental

## Overview

This skill was automatically generated based on:
- Context analysis of recent Claude Hours activity
- Identified capability gaps
- Observed usage patterns

## Description

Automates $skill_name tasks to improve Claude Hours productivity.

## When to Use

Use this skill when:
- Task involves $skill_name
- Need to perform $skill_name operations
- Automation of $skill_name workflows required

## Capabilities

- [ ] Core capability 1
- [ ] Core capability 2
- [ ] Core capability 3

## Implementation

See \`SKILL.md\` in the skill folder for detailed implementation.

## Context

Generated during Claude Hours $(date '+%Y-%m-%d') session.

---

*Auto-generated skill - may require refinement*
EOF
    
    # Generate skill implementation
    cat > "$skill_dir/script.sh" << EOF
#!/bin/bash
# $skill_name implementation

echo "Executing $skill_name..."
# TODO: Implement $skill_name functionality

# Example implementation:
# - Read input parameters
# - Process data
# - Return output

exit 0
EOF
    chmod +x "$skill_dir/script.sh"
    
    # Create skill metadata
    cat > "$skill_dir/.skill-meta.json" << EOF
{
  "name": "$skill_name",
  "created": "$(date '+%Y-%m-%dT%H:%M:%S-06:00')",
  "source": "auto-generated",
  "version": "0.1",
  "status": "experimental",
  "usage_count": 0,
  "success_rate": null,
  "context_patterns": ["$skill_name"]
}
EOF
    
    log "Skill generated: $skill_dir"
    echo "$skill_dir"
}

# === CREATE SWARM-BASED SKILL ===
create_skill_via_swarm() {
    local skill_name="$1"
    local description="$2"
    
    log "Creating skill via swarm: $skill_name"
    
    # Create PRD for the skill
    local prd_file="$CLAWD/system/planning/prds/prd-$(date +%Y-%m-%d)-${skill_name// /-}.md"
    
    cat > "$prd_file" << EOF
# PRD: $skill_name

**Created:** $(date '+%Y-%m-%d')
**Source:** Claude Hours Skill Generator
**Priority:** P1

## Problem
Need to automate $description

## Solution
Create a dedicated skill for $skill_name operations

## Requirements
- Automate $description
- Integrate with Claude Hours
- Track usage and success

## Implementation Plan
1. Research best practices
2. Write core implementation
3. Create documentation
4. Test integration
EOF
    
    # Run swarm to implement
    cd "$CLAWD/skills/agent-swarm"
    node scripts/swarm-orchestrator.js init "Create $skill_name skill: $description. Research best practices, write implementation code, create documentation. Output: new skill folder in /Users/jasontang/clawd/skills/" > /dev/null 2>&1
    
    log "Swarm completed for skill: $skill_name"
}

# === TRACK SKILL PROGRESS ===
track_skill() {
    local skill_name="$1"
    local status="$2"  # created, used, successful, failed
    local details="${3:-}"
    
    log "Tracking skill: $skill_name ($status)"
    
    # Create tracking file if doesn't exist
    if [ ! -f "$TRACKING_FILE" ]; then
        echo '{"skills": {}, "created": [], "used": [], "successes": [], "failures": []}' > "$TRACKING_FILE"
    fi
    
    # Update tracking via jq
    local timestamp=$(date '+%Y-%m-%dT%H:%M:%S-06:00')
    
    case "$status" in
        created)
            jq --arg name "$skill_name" --arg ts "$timestamp" '.created += [{name: $name, time: $ts}]' "$TRACKING_FILE" > "${TRACKING_FILE}.tmp" 2>/dev/null && mv "${TRACKING_FILE}.tmp" "$TRACKING_FILE"
            ;;
        used)
            jq --arg name "$skill_name" --arg ts "$timestamp" '.used += [{name: $name, time: $ts}]' "$TRACKING_FILE" > "${TRACKING_FILE}.tmp" 2>/dev/null && mv "${TRACKING_FILE}.tmp" "$TRACKING_FILE"
            ;;
        successful)
            jq --arg name "$skill_name" --arg ts "$timestamp" '.successes += [{name: $name, time: $ts}]' "$TRACKING_FILE" > "${TRACKING_FILE}.tmp" 2>/dev/null && mv "${TRACKING_FILE}.tmp" "$TRACKING_FILE"
            ;;
        failed)
            jq --arg name "$skill_name" --arg ts "$timestamp" --arg reason "$details" '.failures += [{name: $name, time: $ts, reason: $reason}]' "$TRACKING_FILE" > "${TRACKING_FILE}.tmp" 2>/dev/null && mv "${TRACKING_FILE}.tmp" "$TRACKING_FILE"
            ;;
    esac
    
    # Update skill meta file
    local skill_meta="$SKILLS_DIR/${skill_name// /-}/.skill-meta.json"
    if [ -f "$skill_meta" ]; then
        local count=$(jq '.usage_count' "$skill_meta" 2>/dev/null || echo 0)
        jq --arg status "$status" '.usage_count = (.usage_count + 1) | .last_used = "'$(date '+%Y-%m-%dT%H:%M:%S-06:00')'"' "$skill_meta" > "${skill_meta}.tmp" 2>/dev/null && mv "${skill_meta}.tmp" "$skill_meta"
    fi
}

# === AUTO-DISCOVER AND GENERATE ===
auto_discover() {
    log "Auto-discovering skill needs..."
    
    # Get recent patterns
    local patterns=$(analyze_context)
    local gaps=$(identify_skill_gaps)
    
    local to_create=()
    
    # Combine patterns and gaps
    for pattern in $patterns $gaps; do
        # Check if skill already exists
        if [ ! -d "$SKILLS_DIR/$pattern" ] && [ ! -d "$SKILLS_DIR/${pattern//_/-}" ]; then
            to_create+=("$pattern")
        fi
    done
    
    # Generate up to 2 new skills
    local count=0
    for skill in "${to_create[@]}"; do
        if [ $count -lt 2 ]; then
            log "Auto-creating skill: $skill"
            generate_skill "$skill"
            track_skill "$skill" "created"
            count=$((count + 1))
        fi
    done
    
    if [ $count -gt 0 ]; then
        log "Auto-created $count new skills"
        echo "$count"
    else
        log "No new skills needed"
        echo "0"
    fi
}

# === MAIN ===
main() {
    echo "=============================================="
    echo "   Claude Hours Skill Generator"
    echo "=============================================="
    
    case "${1:-help}" in
        analyze)
            echo "=== Context Analysis ==="
            analyze_context
            ;;
        gaps)
            echo "=== Skill Gaps ==="
            identify_skill_gaps
            ;;
        generate)
            shift
            [ -z "$1" ] && echo "Usage: $0 generate <skill-name>" && exit 1
            generate_skill "$1"
            ;;
        swarm)
            shift
            [ -z "$1" ] && echo "Usage: $0 swarm <skill-name> <description>" && exit 1
            create_skill_via_swarm "$1" "$2"
            ;;
        auto)
            echo "=== Auto-Discover ==="
            auto_discover
            ;;
        track)
            shift
            track_skill "$1" "$2" "$3"
            ;;
        list)
            echo "=== Existing Skills ==="
            ls "$SKILLS_DIR" 2>/dev/null | grep -v "^_\|^system" | head -10 || echo "No skills found"
            ;;
        stats)
            echo "=== Skill Statistics ==="
            if [ -f "$TRACKING_FILE" ]; then
                jq '.' "$TRACKING_FILE" 2>/dev/null || cat "$TRACKING_FILE"
            else
                echo "No tracking data yet"
            fi
            ;;
        help|*)
            echo "Usage: $0 <command> [args]"
            echo ""
            echo "Commands:"
            echo "  analyze              - Analyze context for skill needs"
            echo "  gaps                 - Identify missing skill gaps"
            echo "  generate <name>      - Generate new skill"
            echo "  swarm <name> <desc>  - Create skill via swarm"
            echo "  auto                 - Auto-discover and create skills"
            echo "  track <name> <event> - Track skill usage (created/used/successful/failed)"
            echo "  list                 - List existing skills"
            echo "  stats                - Show skill statistics"
            echo "  help                 - Show this help"
            echo ""
            echo "Examples:"
            echo "  $0 auto"
            echo "  $0 generate 'Web Scraper'"
            echo "  $0 swarm 'API Client' 'Handle API calls and responses'"
            ;;
    esac
}

main "$@"
